version: '3'
services:
  sc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc
    hostname: sc
    ports:
      - "9103:9003"
    environment:
      - RUST_LOG=info
    entrypoint: >
      /bin/sh -c "
      fluvio profile add docker sc:9003 docker;
      fluvio cluster spu register --id 5001 -p spu:9010 --private-server spu:9011;
      fluvio run sc --local /fluvio/metadata;
      exit 0;
      "
  spu:
    image: infinyon/fluvio:latest
    container_name: spu
    hostname: spu
    volumes:
      - fluvio-data:/fluvio/data
    environment:
      - RUST_LOG=info
    ports:
      - "9110:9010"
      - "9111:9011"
    command: "./fluvio-run spu -i 5001 -p spu:9010 -v spu:9011 --sc-addr sc:9003 --log-base-dir /fluvio/data"
volumes:
  fluvio-metadata:
  fluvio-data:
